### ISSUE TITLE
Model Branches: model-cnn und model-hgb erstellen

### ISSUE THREAD

**Issue by buesst1** [Sensor-Based-Activity-Recognition/pipelines#107]

**Comment by gabrieltorresgamez** [comment]
@buesst1 
Wenn möglich noch die Metriken in unserer Dokumentation anpassen/kontrollieren. 

Vorallem in diesen Dateien: 
docs/Modelle.md (CML Report Link und Metriken updaten + Standardabweichungen hinzufügen)
docs/Zusammenfassung.md (Link zur Confusion Matrix updaten und Metriken updaten + Metrics Bild hinzufügen)

Falls dies zu viel wäre kann ich das auch übernehmen, musst mich einfach taggen.
