### ISSUE TITLE
More git integration

### ISSUE THREAD

**Issue by yvokeller** [Sensor-Based-Activity-Recognition/pipelines#41]
@gabrieltorresgamez @yvokeller 

- [x] [https://cml.dev/](https://cml.dev/)
- [x] Github Pipeline (self hosted?)
- [x] self-hosted iterative.ai instance, was das sinn? welche vorteile haben wir?

**Comment by ghost** [comment]
GitHub und Iterative Studio Login erstellt: iterative@fuet.ch -> Passwort bei @gabrieltorresgamez  anfordern

**Comment by gabrieltorresgamez** [comment]
Runner und Workflows wurden erstellt und konfiguriert. Der Runner wurde auf meinem PC zuhause gehostet also müsst ihr mir bescheid geben falls ihr einen run durchführen wollt falls der Runner nicht online ist.

Das fehlt noch:
- [x] Modell und Workflow so konfigurieren, dass nach jedem Commit das Modell trainiert wird und die Metriken zurückgegeben werden.

**Comment by florinbarbisch** [comment]
gabriel ist nicht mehr zu helfen

**Comment by gabrieltorresgamez** [comment]
Wurde konfiguriert und reviewed. Implementation von Plots in den Workflow erfolgt nach #45 
Muss noch mit florin für access auf s3 schauen.
