### ISSUE TITLE
Evaluation stage

### ISSUE THREAD

**Issue by florinbarbisch** [Sensor-Based-Activity-Recognition/pipelines#45]
- Evaluation-stage. Output:
    -  [x] Confusion matrix (png)
    - [x] metrics.txt
    - [x] Optional: plots of loss, accuracy and f1_macro per epoch

**Comment by gabrieltorresgamez** [comment]
alarm, je nach modell in der dvclive stage gibt das modell einen fehler zurück.
https://github.com/Sensor-Based-Activity-Recognition/pipelines/actions/runs/4850200387/jobs/8642891842

Was machen wir hier? @florinbarbisch @yvokeller
