### ISSUE TITLE
Test accuracy analysieren

### ISSUE THREAD

**Issue by florinbarbisch** [Sensor-Based-Activity-Recognition/pipelines#67]
- [x] Problem finden, wieso wir eine schlechte Testaccuracy haben
- [x] Test-Accuracy auf >80% bringen (Segment based train/test split)
Optional:
- [x] Test-Accuracy auf >95% bringen (Segment based train/test split)

**Comment by gabrieltorresgamez** [comment]
Florins Model sehr halal
