### ISSUE TITLE
Nicht alle Parameter von einem Run aus Iterative.ai konfigurierbar.

### ISSUE THREAD

**Issue by florinbarbisch** [Sensor-Based-Activity-Recognition/pipelines#69]
See: [https://studio.iterative.ai/user/cdl1-sensor-data-challenge/projects/pipelines-6fdgjpj1qi?panels=cml-run%2C&commits=7073826%2Cpurple](https://studio.iterative.ai/user/cdl1-sensor-data-challenge/projects/pipelines-6fdgjpj1qi?panels=cml-run%2C&commits=7073826%2Cpurple)

Abnahmekriterien:
- [x] Alle Parameter aus params.yml sind in einem Run aus iterative.ai veränderbar.

**Comment by yvokeller** [comment]
We have to manually configure which Metrics, Params and Files we want to see in iterative studio. Max is 200, and the automatic mode does not make sense as we already have more than that (it takes e.g. the params from each commit, so there would be old params we will never use again). Selected everything manually now as we have it configured in main.

--> We should manually adjust this setting in the future every time a new parameter is added and needs to be configureable.
 
[Column Settings for Project](https://studio.iterative.ai/user/cdl1-sensor-data-challenge/projects/pipelines-6fdgjpj1qi/settings)

<img width="605" alt="image" src="https://user-images.githubusercontent.com/22744751/235467413-fb1cd61d-df34-4e11-a24c-46ef4f0eb618.png">

How it looks now
<img width="638" alt="image" src="https://user-images.githubusercontent.com/22744751/235467870-66a5e7eb-f423-4805-86b0-29c5d105f8c0.png">
