### ISSUE TITLE
Erstes Deep Learning Modell

### ISSUE THREAD

**Issue by buesst1** [Sensor-Based-Activity-Recognition/pipelines#80]
- [x] Nutzen von segmentierten Daten

Wenn möglich: 2D-CNN auf Spectral Map zu Daten trainiert, siehe Research Notizen [Spectrogram Maps](https://github.com/Sensor-Based-Activity-Recognition/docs/blob/main/recherche/Preprocessing%20%26%20Features.md#deep-learning)

- [x] Spektrogramm Stage hinzufügen (Output: 1 Image oder Matrix pro Segment, Input: Segments)
- [x] Pytorch Dataset Class
- [x] Abstract new dataset class
- [x] run on GPU
- [x] optimize params
- [x] delete ipynb
- [x] CPU auslastung bei 100%, DataLoader?
- [ ] Merge Branch into Main

**Comment by buesst1** [comment]
@gabrieltorresgamez -> Help Florin

**Comment by florinbarbisch** [comment]
![image](https://github.com/Sensor-Based-Activity-Recognition/pipelines/assets/40719099/5b92f8d6-728c-4656-aefe-ade5718953ee)

@gabrieltorresgamez cache lösche het ghulfe
